=head1 NAME

TeaJS - Your cup of server-side JavaScript. TeaJS is a wrapper around V8 Javascript engine

=head1 SYNOPSIS

tea [B<-v>] [B<-h>] [B<-w> [B<-d> I<port>]] [B<-c> I<config_file>] I<main_file>

=head1 DESCRIPTION

TeaJS reads the contents of I<main_file> and executes it using the V8 engine. TeaJS implements CommonJS's Modules proposal, which allows for easy distribution of code into several modules. TeaJS ships with many built-in modules; more of them are available as separate packages.

=head1 OPTIONS

=over 8

=item B<-v>

Print TeaJS version

=item B<-h>

Show command line usage help

=item B<-w>

Wait for V8 debugger

=item B<-d I<port>>

Listen for V8 debugger at this port

=item B<-c I<config_file>>

Use a given config file instead of system-wide config file

=back

=head1 SEE ALSO

TeaJS is hosted at Google Code. Its homepage is B<http://code.google.com/p/teajs/>.

=head1 BUGS

Please report bugs at B<http://code.google.com/p/teajs/issues/list>.

=head1 AUTHORS

B<TeaJS> was written by Ondrej Zara <ondrej.zara@gmail.com>. It is released under the New BSD Licence.

=cut
